#!/usr/bin/env bash
# scripts/export-contract-ids.sh
#
# Print all deployed contract IDs from the Stellar network by alias.
# Reads STELLAR_NETWORK (default: testnet) and queries the account's
# deployed contracts via stellar contract alias list.
#
# Usage:
#   ./scripts/export-contract-ids.sh
#   ./scripts/export-contract-ids.sh mainnet

set -euo pipefail

NETWORK="${1:-${NETWORK:-testnet}}"

ALIASES=(
  "kora-invoice-nft"
  "kora-marketplace"
  "kora-financing-pool"
  "kora-treasury"
  "kora-risk-registry"
  "kora-access-control"
)

echo "# Kora Protocol contract IDs on $NETWORK"
echo "# Generated by scripts/export-contract-ids.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo

for alias in "${ALIASES[@]}"; do
  id=$(stellar contract alias show "$alias" --network "$NETWORK" 2>/dev/null || echo "NOT_DEPLOYED")
  printf "%-30s %s\n" "$alias" "$id"
done
